routes/web.php
    Route::get('/disciplines/summary/{id}','ExploreController@disciplineSummary')
        ->name('explore.discipline.summary')
        ->where('id', '[0-9]+');
    
    Route::get('/disciplines/published/{id}','ExploreController@latestPublished')
        ->name('explore.discipline.published')
        ->where('id', '[0-9]+');
    
    Route::get('/disciplines/draft/{id}','ExploreController@latestDraft')
        ->name('explore.discipline.draft')
        ->where('id', '[0-9]+');
    
    Route::get('/disciplines/draft/skill/{id}','ExploreController@latestDraftSkillWise')
        ->name('explore.discipline.draft.skill')
        ->where('id', '[0-9]+');    
    Route::get('/curriculumn/exercisesets','ExploreController@curriculumnExerciseset')
        ->name('explore.curriculum.exerciseset');
    Route::get('/curriculumn/classes','ExploreController@curriculumnClasses')
        ->name('explore.curriculum.classes');

    Route::get('/curriculumn/skill-list/{curriculumn_id}','ExploreController@getCurriculumSkillList')
        ->name('explore.curriculum.skill-list');
    
});

Auth::routes();

// Unauthorized
Route::get('/unauthorized', function () {
    return redirect('/public');
})->name('unauthorized');

Route::get('auth/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('auth/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

// Role
Route::group(
    [
        'prefix' => 'roles',
    ], function () {

   /* Route::get('/', 'RolesController@listroles')
        ->name('roles.list');*/
});

// Schools
Route::group(
    [
        'prefix' => 'schools',
    ], function () {

    Route::get('/', 'SchoolsController@index')
        ->name('schools.school.index');

    Route::get('/create','SchoolsController@create')
        ->name('schools.school.create');

    Route::get('/show/{school}','SchoolsController@show')
        ->name('schools.school.show')
        ->where('id', '[0-9]+');

    Route::get('/{school}/edit','SchoolsController@edit')
        ->name('schools.school.edit')
        ->where('id', '[0-9]+');

    Route::post('/', 'SchoolsController@store')
        ->name('schools.school.store');

    Route::put('school/{school}', 'SchoolsController@update')
        ->name('schools.school.update')
        ->where('id', '[0-9]+');

    Route::delete('/school/{school}','SchoolsController@destroy')
        ->name('schools.school.destroy')
        ->where('id', '[0-9]+');

});

// Countries
Route::group(
[
    'prefix' => 'countries',
], function () {

    Route::get('/', 'CountriesController@index')
         ->name('countries.country.index');

    Route::get('/create','CountriesController@create')
         ->name('countries.country.create');

    Route::get('/show/{country}','CountriesController@show')
         ->name('countries.country.show')
         ->where('id', '[0-9]+');

    Route::get('/{country}/edit','CountriesController@edit')
         ->name('countries.country.edit')
         ->where('id', '[0-9]+');

    Route::post('/', 'CountriesController@store')
         ->name('countries.country.store');

    Route::put('country/{country}', 'CountriesController@update')
         ->name('countries.country.update')
         ->where('id', '[0-9]+');

    Route::delete('/country/{country}','CountriesController@destroy')
         ->name('countries.country.destroy')
         ->where('id', '[0-9]+');

});

// Curricula
Route::group(
    [
        'prefix' => 'curriculum_gradelists',
    ], function () {

    Route::get('/', 'Disciplines\Curriculum_gradelistsController@index')
        ->name('curriculum_gradelists.curriculum.index');

    Route::get('/create','Disciplines\Curriculum_gradelistsController@create')
        ->name('curriculum_gradelists.curriculum.create');

    Route::get('/show/{curriculum}','Disciplines\Curriculum_gradelistsController@show')
        ->name('curriculum_gradelists.curriculum.show')
        ->where('id', '[0-9]+');

    Route::get('/{curriculum}/edit','Disciplines\Curriculum_gradelistsController@edit')
        ->name('curriculum_gradelists.curriculum.edit')
        ->where('id', '[0-9]+');

    Route::post('/', 'Disciplines\Curriculum_gradelistsController@store')
        ->name('curriculum_gradelists.curriculum.store');

    Route::put('curriculum/{curriculum}', 'Disciplines\Curriculum_gradelistsController@update')
        ->name('curriculum_gradelists.curriculum.update')
        ->where('id', '[0-9]+');

    Route::delete('/curriculum/{curriculum}','Disciplines\Curriculum_gradelistsController@destroy')
        ->name('curriculum_gradelists.curriculum.destroy')
        ->where('id', '[0-9]+');

});

// Grades
Route::group(
[
    'prefix' => 'grades',
], function () {

    Route::get('/', 'Disciplines\GradesController@index')
         ->name('grades.grade.index');

   Route::post('/create/{id}','Disciplines\GradesController@create')
       ->name('grades.grade.create');

    Route::get('/create/{id}','Disciplines\GradesController@create')
       ->name('grades.grade.create');

    Route::get('/show/{grade}','Disciplines\GradesController@show')
         ->name('grades.grade.show')
         ->where('id', '[0-9]+');

    Route::get('/{grade}/edit','Disciplines\GradesController@edit')
         ->name('grades.grade.edit')
         ->where('id', '[0-9]+');

    Route::post('/', 'Disciplines\GradesController@store')
         ->name('grades.grade.store');

    Route::put('grade/{grade}', 'Disciplines\GradesController@update')
         ->name('grades.grade.update')
         ->where('id', '[0-9]+');

    Route::delete('/grade/{grade}','Disciplines\GradesController@destroy')
         ->name('grades.grade.destroy')
         ->where('id', '[0-9]+');

});

// Activities
Route::group(
[
    'prefix' => 'activities',
], function () {

    Route::get('/', 'ActivitiesController@index')
         ->name('activities.activity.index');

    Route::get('/create','ActivitiesController@create')
         ->name('activities.activity.create');

    Route::get('/show/{activity}','ActivitiesController@show')
         ->name('activities.activity.show')
         ->where('id', '[0-9]+');

    Route::get('/{activity}/edit','ActivitiesController@edit')
         ->name('activities.activity.edit')
         ->where('id', '[0-9]+');

    Route::post('/', 'ActivitiesController@store')
         ->name('activities.activity.store');

    Route::put('activity/{activity}', 'ActivitiesController@update')
         ->name('activities.activity.update')
         ->where('id', '[0-9]+');

    Route::delete('/activity/{activity}','ActivitiesController@destroy')
         ->name('activities.activity.destroy')
         ->where('id', '[0-9]+');

});

// Badges
Route::group(
[
    'prefix' => 'badges',
], function () {

    Route::get('/', 'BadgesController@index')
         ->name('badges.badge.index');

    Route::get('/create','BadgesController@create')
         ->name('badges.badge.create');

    Route::get('/show/{badge}','BadgesController@show')
         ->name('badges.badge.show')
         ->where('id', '[0-9]+');

    Route::get('/{badge}/edit','BadgesController@edit')
         ->name('badges.badge.edit')
         ->where('id', '[0-9]+');

    Route::post('/', 'BadgesController@store')
         ->name('badges.badge.store');

    Route::put('badge/{badge}', 'BadgesController@update')
         ->name('badges.badge.update')
         ->where('id', '[0-9]+');

    Route::delete('/badge/{badge}','BadgesController@destroy')
         ->name('badges.badge.destroy')
         ->where('id', '[0-9]+');

});

// Business rules
Route::group(
[
    'prefix' => 'businessrules',
], function () {

    Route::get('/', 'BusinessrulesController@index')
         ->name('businessrules.businessrule.index');

    Route::get('/create','BusinessrulesController@create')
         ->name('businessrules.businessrule.create');

    Route::get('/show/{businessrule}','BusinessrulesController@show')
         ->name('businessrules.businessrule.show')
         ->where('id', '[0-9]+');

    Route::get('/{businessrule}/edit','BusinessrulesController@edit')
         ->name('businessrules.businessrule.edit')
         ->where('id', '[0-9]+');

    Route::post('/', 'BusinessrulesController@store')
         ->name('businessrules.businessrule.store');

    Route::put('businessrule/{businessrule}', 'BusinessrulesController@update')
         ->name('businessrules.businessrule.update')
         ->where('id', '[0-9]+');

    Route::delete('/businessrule/{businessrule}','BusinessrulesController@destroy')
         ->name('businessrules.businessrule.destroy')
         ->where('id', '[0-9]+');

});

// Invited users
Route::group(
    [
        'prefix' => 'invitedusers',
    ], function () {

    Route::get('/', 'User\InvitedusersController@index')
        ->name('invitedusers.inviteduser.index');

    Route::get('/create','User\InvitedusersController@create')
        ->name('invitedusers.inviteduser.create');

    Route::get('/show/{inviteduser}','User\InvitedusersController@show')
        ->name('invitedusers.inviteduser.show')
        ->where('id', '[0-9]+');


    Route::get('/{inviteduser}/edit','User\InvitedusersController@edit')
        ->name('invitedusers.inviteduser.edit')
        ->where('id', '[0-9]+');

    Route::post('/', 'User\InvitedusersController@store')
        ->name('invitedusers.inviteduser.store');

    Route::post('/profile', 'User\InvitedusersController@store_profile')
        ->name('invitedusers.inviteduser.store_profile');

    Route::put('inviteduser/{inviteduser}', 'User\InvitedusersController@update')
        ->name('invitedusers.inviteduser.update')
        ->where('id', '[0-9]+');

    Route::delete('/inviteduser/{inviteduser}','User\InvitedusersController@destroy')
        ->name('invitedusers.inviteduser.destroy')
        ->where('id', '[0-9]+');

    //Develop by Wc
    Route::get('/child/password-change','User\InvitedusersController@childResetPassword')->name('child-password-change');
});

// Languages
Route::group(
    [

app/Models/Game.php
<?php

namespace App\Models;


use Trexology\ReviewRateable\Contracts\ReviewRateable;
use Trexology\ReviewRateable\Traits\ReviewRateable as ReviewRateableTrait;
use Illuminate\Database\Eloquent\Model;

class Game extends Model implements ReviewRateable
{
    use ReviewRateableTrait;

    protected $table = 'games';
    protected $primaryKey = 'id';

    protected $fillable = [
                  'discipline_id',
                  'developer_id',
                  'game_name',
                  'patform',
                  'app_id',
                  'secrete_key',
                  'game_icon',
                  'image1',
                  'image2',
                  'image3',
                  'image4',
                  'image5',
                  'category_id',
                  'age_id',
                  'status',
                  'isapproved',
                  'isactive',
                  'description'
              ];

    protected $dates = [];
    protected $casts = [];
    
    /**
     * Get the discipline that this game is designed for. 0 is for all
     */
    public function discipline()
    {
        return $this->belongsTo('App\Models\Discipline','discipline_id');
    }

    /**
     * Get the developer of this game
     */
    public function developer()
    {
        return $this->belongsTo('App\Models\User','developer_id');
    }

    /**
     * Get the users who downloaded this game --TODO Use it in admin views
     */
    public function downloaders(){
        return $this->belongsToMany('App\Models\User','gamedownloads','game_id','user_id','id' );
    }

    //Get created_at Attribute
    public function getCreatedAtAttribute($value)
    {
        return date('j/n/Y g:i A', strtotime($value));
    }

    //Get update_at Attribute
    public function getUpdatedAtAttribute($value)
    {
        return date('j/n/Y g:i A', strtotime($value));
    }

}

resources/views/curricula/create.blade.php
@extends('layouts.admin')

@section('content')

    <div class="panel panel-default">

        <div class="panel-heading clearfix">
            
            <span class="pull-left">
                <h4 class="mt-5 mb-5">Create New Curriculum</h4>
            </span>

            <div class="btn-group btn-group-sm pull-right" role="group">
                <a href="{{ route('curricula.curriculum.index') }}" class="btn btn-primary" title="Show All Curriculum">
                    <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                </a>
            </div>

        </div>

        <div class="panel-body">
        
            @if ($errors->any())
                <ul class="alert alert-danger">
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            @endif

            <form method="POST" action="{{ route('curricula.curriculum.store') }}" accept-charset="UTF-8" id="create_curriculum_form" name="create_curriculum_form" class="form-horizontal">
            {{ csrf_field() }}
            @include ('curricula.form', [
                                        'curriculum' => null,
                                      ])

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input class="btn btn-primary" type="submit" value="Add">
                    </div>
                </div>

            </form>

        </div>
    </div>

@endsection

resources/views/curricula/edit.blade.php
@extends('layouts.admin')

@section('content')

    <div class="panel panel-default">
  
        <div class="panel-heading clearfix">

            <div class="pull-left">
                <h4 class="mt-5 mb-5">{{ !empty($title) ? $title : 'Curriculum' }}</h4>
            </div>
            <div class="btn-group btn-group-sm pull-right" role="group">

                <a href="{{ route('curricula.curriculum.index') }}" class="btn btn-primary" title="Show All Curriculum">
                    <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                </a>

                <a href="{{ route('curricula.curriculum.create') }}" class="btn btn-success" title="Create New Curriculum">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                </a>

            </div>
        </div>

        <div class="panel-body">

            @if ($errors->any())
                <ul class="alert alert-danger">
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            @endif

            <form method="POST" action="{{ route('curricula.curriculum.update', $curriculum->id) }}" id="edit_curriculum_form" name="edit_curriculum_form" accept-charset="UTF-8" class="form-horizontal">
            {{ csrf_field() }}
            <input name="_method" type="hidden" value="PUT">
            @include ('curricula.form', [
                                        'curriculum' => $curriculum,
                                      ])

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input class="btn btn-primary" type="submit" value="Update">
                    </div>
                </div>
            </form>

        </div>
    </div>

@endsection

resources/views/curricula/form.blade.php
<div class="form-group {{ $errors->has('curriculum_gradelist_name') ? 'has-error' : '' }}">
    <label for="curriculum_gradelist_name" class="col-md-2 control-label">Curriculum Name</label>
    <div class="col-md-10">
        <input class="form-control" name="curriculum_gradelist_name" type="text" id="curriculum_ Grade list name" value="{{ old('curriculum_gradelist_name', optional($curriculum)->curriculum_gradelist_name) }}" minlength="1" maxlength="250" required="true" placeholder="Enter curriculum name here...">
        {!! $errors->first('curriculum_gradelist_name', '<p class="help-block">:message</p>') !!}
    </div>
</div>

<div class="form-group {{ $errors->has('description') ? 'has-error' : '' }}">
    <label for="description" class="col-md-2 control-label">Description</label>
    <div class="col-md-10">
        <textarea class="form-control" name="description" cols="50" rows="10" id="description" required="true">{{ old('description', optional($curriculum)->description) }}</textarea>
        {!! $errors->first('description', '<p class="help-block">:message</p>') !!}
    </div>
</div>

<div class="form-group {{ $errors->has('country_id') ? 'has-error' : '' }}">
    <label for="country_id" class="col-md-2 control-label">Country</label>
    <div class="col-md-10">
        <select class="form-control" id="country_id" name="country_id" required="true">
        	    <option value="" style="display: none;" {{ old('country_id', optional($curriculum)->country_id ?: '') == '' ? 'selected' : '' }} disabled selected>Enter country here...</option>
        	@foreach ($countries as $key => $country)
			    <option value="{{ $key }}" {{ old('country_id', optional($curriculum)->country_id) == $key ? 'selected' : '' }}>
			    	{{ $country }}
			    </option>
			@endforeach
        </select>
        
        {!! $errors->first('country_id', '<p class="help-block">:message</p>') !!}
    </div>
</div>

<div class="form-group {{ $errors->has('approve_status') ? 'has-error' : '' }}">
    <label for="approve_status" class="col-md-2 control-label">Approve Status</label>
    <div class="col-md-10">
        <select class="form-control" id="approve_status" name="approve_status" required="true">
        	    <option value="" style="display: none;" {{ old('approve_status', optional($curriculum)->approve_status ?: '') == '' ? 'selected' : '' }} disabled selected>Enter approve status here...</option>
        	@foreach (['pending' => 'Pending',
'approved' => 'Approved',
'declined' => 'Declined',
'' => ''] as $key => $text)
			    <option value="{{ $key }}" {{ old('approve_status', optional($curriculum)->approve_status) == $key ? 'selected' : '' }}>
			    	{{ $text }}
			    </option>
			@endforeach
        </select>
        
        {!! $errors->first('approve_status', '<p class="help-block">:message</p>') !!}
    </div>
</div>

<div class="form-group {{ $errors->has('createdby') ? 'has-error' : '' }}">
    <label for="createdby" class="col-md-2 control-label">Createdby</label>
    <div class="col-md-10">
        <input class="form-control" name="createdby" type="number" id="createdby" value="{{ old('createdby', optional($curriculum)->createdby) }}" min="-2147483648" max="2147483647" required="true" placeholder="Enter createdby here...">
        {!! $errors->first('createdby', '<p class="help-block">:message</p>') !!}
    </div>
</div>

<div class="form-group {{ $errors->has('updatedby') ? 'has-error' : '' }}">
    <label for="updatedby" class="col-md-2 control-label">Updatedby</label>
    <div class="col-md-10">
        <input class="form-control" name="updatedby" type="number" id="updatedby" value="{{ old('updatedby', optional($curriculum)->updatedby) }}" min="-2147483648" max="2147483647" required="true" placeholder="Enter updatedby here...">
        {!! $errors->first('updatedby', '<p class="help-block">:message</p>') !!}
    </div>
</div>

resources/views/curricula/index.blade.php
@extends('layouts.admin')

@section('content')

    @if(Session::has('success_message'))
        <div class="alert alert-success">
            <span class="glyphicon glyphicon-ok"></span>
            {!! session('success_message') !!}

            <button type="button" class="close" data-dismiss="alert" aria-label="close">
                <span aria-hidden="true">&times;</span>
            </button>

        </div>
    @endif

    <div class="panel panel-default">

        <div class="panel-heading clearfix">

            <div class="pull-left">
                <h4 class="mt-5 mb-5">Curricula Grade List</h4>
            </div>

            <div class="btn-group btn-group-sm pull-right" role="group">
                <a href="{{ route('curricula.curriculum.create') }}" class="btn btn-success" title="Create New Curriculum">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                </a>
            </div>

        </div>
        
        @if(count($curricula) == 0)
            <div class="panel-body text-center">
                <h4>No Curricula Grade Lists Available!</h4>
            </div>
        @else
        <div class="panel-body panel-body-with-table">
            <div class="table-responsive">

                <table class="table table-striped ">
                    <thead>
                        <tr>
                            <th>Grade List Name</th>

                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach($curricula as $curriculum)
                        <tr>
                            <td>{{ $curriculum->curriculum_gradelist_name }}</td>

                            <td>

                                <form method="POST" action="{!! route('curricula.curriculum.destroy', $curriculum->id) !!}" accept-charset="UTF-8">
                                <input name="_method" value="DELETE" type="hidden">
                                {{ csrf_field() }}

                                    <div class="btn-group btn-group-xs pull-right" role="group">
                                        <a href="{{ route('curricula.curriculum.show', $curriculum->id ) }}" class="btn btn-info" title="Show Curriculum">
                                            <span class="glyphicon glyphicon-open" aria-hidden="true"></span>
                                        </a>
                                        <a href="{{ route('curricula.curriculum.edit', $curriculum->id ) }}" class="btn btn-primary" title="Edit Curriculum">
                                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                        </a>

                                        <button type="submit" class="btn btn-danger" title="Delete Curriculum" onclick="return confirm('Delete Curriculum?')">
                                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                        </button>
                                    </div>

                                </form>
                                
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>

            </div>
        </div>

        <div class="panel-footer">
            {!! $curricula->render() !!}
        </div>
        
        @endif
    
    </div>
@endsection

resources/views/curricula/show.blade.php
@extends('layouts.admin')

@section('content')

<div class="panel panel-default">
    <div class="panel-heading clearfix">

        <span class="pull-left">
            <h4 class="mt-5 mb-5">{{ isset($title) ? $title : 'Curriculum' }}</h4>
        </span>

        <div class="pull-right">

            <form method="POST" action="{!! route('curricula.curriculum.destroy', $curriculum->id) !!}" accept-charset="UTF-8">
            <input name="_method" value="DELETE" type="hidden">
            {{ csrf_field() }}
                <div class="btn-group btn-group-sm" role="group">
                    <a href="{{ route('curricula.curriculum.index') }}" class="btn btn-primary" title="Show All Curriculum">
                        <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                    </a>

                    <a href="{{ route('curricula.curriculum.create') }}" class="btn btn-success" title="Create New Curriculum">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                    </a>
                    
                    <a href="{{ route('curricula.curriculum.edit', $curriculum->id ) }}" class="btn btn-primary" title="Edit Curriculum">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                    </a>

                    <button type="submit" class="btn btn-danger" title="Delete Curriculum" onclick="return confirm('Delete Curriculum?')">
                        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                    </button>
                </div>
            </form>

        </div>

    </div>

    <div class="panel-body">
        <dl class="dl-horizontal">
            <dt>Curriculum Name</dt>
            <dd>{{ $curriculum->curriculum_gradelist_name }}</dd>
            <dt>Description</dt>
            <dd>{{ $curriculum->description }}</dd>
            <dt>Country</dt>
            <dd>{{ optional($curriculum->country)->country_name }}</dd>
            <dt>Approve Status</dt>
            <dd>{{ $curriculum->approve_status }}</dd>
            <dt>Createdby</dt>
            <dd>{{ $curriculum->createdby }}</dd>
            <dt>Updatedby</dt>
            <dd>{{ $curriculum->updatedby }}</dd>
            <dt>Created At</dt>
            <dd>{{ $curriculum->created_at }}</dd>
            <dt>Updated At</dt>
            <dd>{{ $curriculum->updated_at }}</dd>

        </dl>

    </div>
</div>

@endsection